import type{MapEntry}from'@pinory/shared';import{api}from'./api';
const loadImage=async(url:string)=>{const blob=await fetch(url,{mode:'cors'}).then(r=>r.blob());const image=new Image();image.src=URL.createObjectURL(blob);await image.decode();return image};
const rounded=(ctx:CanvasRenderingContext2D,x:number,y:number,w:number,h:number,r:number)=>{ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.clip()};
const distanceKm=(a:{lat:number;lng:number},b:{lat:number;lng:number})=>{const rad=(v:number)=>v*Math.PI/180;const dLat=rad(b.lat-a.lat),dLng=rad(b.lng-a.lng);const x=Math.sin(dLat/2)**2+Math.cos(rad(a.lat))*Math.cos(rad(b.lat))*Math.sin(dLng/2)**2;return Math.round(6371*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x)))};
export async function shareEntryCard(entry:MapEntry){const [linkData,me]=await Promise.all([api.telegramShareLink(`entry_${entry.id}`),api.me()]);const link=linkData.url;const fromHome=me.homeCoordinates?distanceKm(me.homeCoordinates,entry.place.coordinates):null;const canvas=document.createElement('canvas');canvas.width=1080;canvas.height=1350;const c=canvas.getContext('2d')!;c.fillStyle='#f7f1e5';c.fillRect(0,0,1080,1350);c.fillStyle='#173c34';c.fillRect(0,0,1080,96);c.fillStyle='#fffdf8';c.font='700 34px Onest';c.fillText('PINORY · ЖИВОЙ АТЛАС',64,62);
 c.save();rounded(c,56,140,968,640,44);if(entry.media[0]){try{const image=await loadImage(entry.media[0].originalUrl);const scale=Math.max(968/image.width,640/image.height);c.drawImage(image,(968-image.width*scale)/2+56,(640-image.height*scale)/2+140,image.width*scale,image.height*scale)}catch{c.fillStyle='#d9e9df';c.fillRect(56,140,968,640)}}else{const g=c.createLinearGradient(56,140,1024,780);g.addColorStop(0,'#ef6c56');g.addColorStop(1,'#169a8f');c.fillStyle=g;c.fillRect(56,140,968,640);c.fillStyle='rgba(255,255,255,.9)';c.font='700 84px Unbounded';c.fillText(entry.place.name.slice(0,18),110,460)}c.restore();
 c.fillStyle='#173c34';c.font='700 58px Unbounded';const title=entry.place.name.length>25?`${entry.place.name.slice(0,24)}…`:entry.place.name;c.fillText(title,64,866);c.fillStyle='#63736e';c.font='600 29px Onest';c.fillText([entry.place.city,entry.place.countryName].filter(Boolean).join(' · ')||'Место на карте',66,918);c.fillStyle='#ef6c56';c.font='700 25px Onest';c.fillText(entry.entryType==='VISITED'?'Я здесь был':'Хочу побывать',66,973);if(entry.visitDate){c.fillStyle='#63736e';c.fillText(new Date(entry.visitDate).toLocaleDateString('ru-RU',{day:'numeric',month:'long',year:'numeric'}),280,973)}
 if(fromHome!==null){c.textAlign='right';c.fillStyle='#63736e';c.fillText(`${fromHome} км от дома`,800,973);c.textAlign='left'}
 if(entry.description){c.fillStyle='#173c34';c.font='500 26px Onest';const words=entry.description.split(/\s+/);let line='';let y=1035;for(const word of words){const test=`${line}${word} `;if(c.measureText(test).width>680){c.fillText(line,66,y);line=`${word} `;y+=38;if(y>1148)break}else line=test}if(y<=1148)c.fillText(line,66,y)}
 const QR=(await import('qrcode')).default;const qr=await QR.toDataURL(link,{margin:1,width:180,color:{dark:'#173c34',light:'#fffdf8'}});const qrImage=new Image();qrImage.src=qr;await qrImage.decode();c.drawImage(qrImage,830,1028,180,180);c.fillStyle='#63736e';c.font='600 20px Onest';c.fillText('Открыть место',836,1238);c.fillStyle='#173c34';c.font='700 26px Onest';c.fillText(`@${entry.author.displayName}`,66,1265);c.fillStyle='#ef6c56';c.fillRect(64,1292,952,6);
 const blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(value=>value?resolve(value):reject(new Error('Не удалось создать карточку')),'image/png',.94));const file=new File([blob],`pinory-${entry.place.name.replace(/[^a-zа-я0-9]+/gi,'-').toLowerCase()}.png`,{type:'image/png'});if(navigator.canShare?.({files:[file]})){await navigator.share({title:entry.place.name,text:'Моё место в Pinory',url:link,files:[file]})}else{const url=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=url;anchor.download=file.name;anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
}
