import{useEffect,useState}from'react';import{useQuery,useQueryClient}from'@tanstack/react-query';import{AnimatePresence,motion}from'motion/react';import{Map,Compass,Plus,Search,UserRound,WifiOff,Send}from'lucide-react';import type{User}from'@pinory/shared';import{api,authenticate}from'./lib/api';import{telegram}from'./lib/telegram';import{t}from'./i18n/ru';import{useAppStore,type Screen}from'./store';import{Logo}from'./components/Logo';import{Onboarding}from'./components/Onboarding';import{MapScreen}from'./screens/MapScreen';import{FeedScreen}from'./screens/FeedScreen';import{SearchScreen}from'./screens/SearchScreen';import{ProfileScreen}from'./screens/ProfileScreen';import{AddEntrySheet}from'./components/AddEntrySheet';import{EntrySheet}from'./components/EntrySheet';import{CollectionSheet}from'./components/CollectionSheet';import{NotificationsSheet}from'./components/NotificationsSheet';

async function bootstrap(){try{return await api.me();}catch{return authenticate();}}
export function App(){const queryClient=useQueryClient();const screen=useAppStore((s)=>s.screen);const selected=useAppStore((s)=>s.selected);const collectionId=useAppStore((s)=>s.selectedCollectionId);const addOpen=useAppStore((s)=>s.addOpen);const notificationsOpen=useAppStore((s)=>s.notificationsOpen);const[online,setOnline]=useState(navigator.onLine);const auth=useQuery({queryKey:['me'],queryFn:bootstrap,retry:1});
  useEffect(()=>{telegram.ready();document.documentElement.dataset.theme=telegram.theme;const on=()=>setOnline(true),off=()=>setOnline(false);addEventListener('online',on);addEventListener('offline',off);return()=>{removeEventListener('online',on);removeEventListener('offline',off);};},[]);
  if(auth.isLoading)return <div className="splash"><Logo large/><div className="splash-orbit"><i/><i/><i/></div><p>{t.loading}</p></div>;
  if(auth.isError||!auth.data)return <div className="error-page"><Logo/><div className="telegram-gate"><Send/></div><h1>Откройте Pinory в Telegram</h1><p>Для входа нужна защищённая сессия Telegram Mini App. Демо-пользователи отключены.</p><button className="primary" onClick={()=>auth.refetch()}>{t.retry}</button></div>;
  if(!auth.data.isOnboardingCompleted)return <Onboarding onDone={async()=>{const user=await api.updateMe({isOnboardingCompleted:true});queryClient.setQueryData(['me'],user);}}/>;
  return <div className="app-shell">{!online&&<div className="offline"><WifiOff size={15}/>{t.offline}</div>}<main className="screen-stage"><AnimatePresence mode="wait" initial={false}><motion.div className="screen-motion" key={screen} initial={{opacity:0,y:8,scale:.995}} animate={{opacity:1,y:0,scale:1}} exit={{opacity:0,y:-5}} transition={{duration:.22,ease:[.2,.8,.2,1]}}>{screen==='map'&&<MapScreen/>}{screen==='feed'&&<FeedScreen/>}{screen==='search'&&<SearchScreen/>}{screen==='profile'&&<ProfileScreen user={auth.data as User}/>}</motion.div></AnimatePresence></main><BottomNav screen={screen}/><AnimatePresence>{addOpen&&<AddEntrySheet/>}{selected&&<EntrySheet entry={selected}/>} {collectionId&&<CollectionSheet id={collectionId}/>} {notificationsOpen&&<NotificationsSheet/>}</AnimatePresence></div>;
}
function BottomNav({screen}:{screen:Screen}){const setScreen=useAppStore((s)=>s.setScreen);const setAddOpen=useAppStore((s)=>s.setAddOpen);const items=[['map',Map,t.nav.map],['feed',Compass,t.nav.feed],['add',Plus,t.nav.add],['search',Search,t.nav.search],['profile',UserRound,t.nav.profile]] as const;return <nav className="bottom-nav" aria-label="Основная навигация">{items.map(([id,Icon,label])=>id==='add'?<motion.button whileTap={{scale:.9}} key={id} className="nav-add" onClick={()=>{telegram.haptic('medium');setAddOpen(true)}} aria-label={label}><span><Icon size={27}/></span><small>{label}</small></motion.button>:<motion.button whileTap={{scale:.9}} key={id} className={screen===id?'active':''} onClick={()=>{telegram.haptic();setScreen(id)}}><Icon size={21}/><small>{label}</small></motion.button>)}</nav>}
