import React from 'react';
import { createRoot } from 'react-dom/client';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import '@fontsource-variable/onest';
import '@fontsource-variable/unbounded';
import 'maplibre-gl/dist/maplibre-gl.css';
import './styles.css';
import './contrast-fixes.css';
import './polish.css';
import './onboarding-polish.css';
import './features.css';
import './social-features.css';
import './interaction-fixes.css';
import './layout-fixes.css';
import './dark-theme.css';
import './native.css';
import './atlas-update.css';
import './share-card.css';
import { App } from './App';

const client = new QueryClient({ defaultOptions: { queries: { staleTime: 30_000, retry: 2, refetchOnWindowFocus: false, gcTime: 10 * 60_000 } } });
createRoot(document.getElementById('root')!).render(<React.StrictMode><QueryClientProvider client={client}><App /></QueryClientProvider></React.StrictMode>);
