import type { FastifyPluginAsync } from 'fastify';
import { CreateCollectionSchema } from '@pinory/shared';
import { z } from 'zod';
import { pool, tx } from '../db.js';
import { requireUser } from '../auth.js';
import { entrySelect, serializeEntry } from '../serializers.js';

const collectionSelect=`SELECT c.*,u.display_name,u.avatar_url,u.telegram_username,
  EXISTS(SELECT 1 FROM collection_follows WHERE collection_id=c.id AND user_id=$2) is_following,
  COALESCE(m.medium_url,(SELECT m2.medium_url FROM collection_entries ce JOIN map_entry_media em ON em.map_entry_id=ce.map_entry_id JOIN media m2 ON m2.id=em.media_id WHERE ce.collection_id=c.id AND m2.deleted_at IS NULL ORDER BY ce.sort_order,em.sort_order LIMIT 1)) cover_url
  FROM collections c JOIN users u ON u.id=c.user_id LEFT JOIN media m ON m.id=c.cover_media_id`;
const serializeCollection=(r:any)=>({id:r.id,userId:r.user_id,title:r.title,description:r.description,visibility:r.visibility,coverUrl:r.cover_url,placesCount:Number(r.places_count),followersCount:Number(r.followers_count),isFollowing:r.is_following,createdAt:r.created_at,author:{id:r.user_id,displayName:r.display_name,avatarUrl:r.avatar_url,telegramUsername:r.telegram_username}});

export const collectionRoutes: FastifyPluginAsync=async(app)=>{
  app.post('/collections',{preHandler:requireUser},async(request,reply)=>{const input=CreateCollectionSchema.parse(request.body);const id=await tx(async(client)=>{const result=await client.query('INSERT INTO collections(user_id,title,description,visibility) VALUES($1,$2,$3,$4) RETURNING id',[request.user.sub,input.title,input.description??null,input.visibility]);for(let i=0;i<input.entryIds.length;i++)await client.query('INSERT INTO collection_entries(collection_id,map_entry_id,sort_order) SELECT $1,$2,$3 WHERE EXISTS(SELECT 1 FROM map_entries WHERE id=$2 AND user_id=$4 AND deleted_at IS NULL) ON CONFLICT DO NOTHING',[result.rows[0].id,input.entryIds[i],i,request.user.sub]);await client.query('UPDATE collections SET places_count=(SELECT count(DISTINCT e.place_id) FROM collection_entries ce JOIN map_entries e ON e.id=ce.map_entry_id WHERE ce.collection_id=$1) WHERE id=$1',[result.rows[0].id]);return result.rows[0].id;});const result=await pool.query(`${collectionSelect} WHERE c.id=$1`,[id,request.user.sub]);return reply.code(201).send(serializeCollection(result.rows[0]));});

  app.get('/collections/:id',{preHandler:requireUser},async(request,reply)=>{const{id}=z.object({id:z.string().uuid()}).parse(request.params);const result=await pool.query(`${collectionSelect} WHERE c.id=$1 AND c.deleted_at IS NULL AND pinory_entry_visible(c.user_id,c.visibility,$2)`,[id,request.user.sub]);if(!result.rows[0])return reply.code(404).send({code:'COLLECTION_NOT_FOUND',message:'Подборка не найдена или недоступна'});const entries=await pool.query(`${entrySelect} JOIN collection_entries ce ON ce.map_entry_id=e.id WHERE ce.collection_id=$1 AND e.deleted_at IS NULL AND pinory_entry_visible(e.user_id,e.visibility,$2) ORDER BY ce.sort_order`,[id,request.user.sub]);return{...serializeCollection(result.rows[0]),entries:entries.rows.map(serializeEntry)};});
  app.get('/users/:id/collections',{preHandler:requireUser},async(request)=>{const{id}=z.object({id:z.string().uuid()}).parse(request.params);const result=await pool.query(`${collectionSelect} WHERE c.user_id=$1 AND c.deleted_at IS NULL AND pinory_entry_visible(c.user_id,c.visibility,$2) ORDER BY c.created_at DESC`,[id,request.user.sub]);return{items:result.rows.map(serializeCollection),nextCursor:null};});
  app.patch('/collections/:id',{preHandler:requireUser},async(request,reply)=>{const{id}=z.object({id:z.string().uuid()}).parse(request.params);const input=CreateCollectionSchema.partial().omit({entryIds:true}).parse(request.body);const current=await pool.query('SELECT * FROM collections WHERE id=$1 AND user_id=$2 AND deleted_at IS NULL',[id,request.user.sub]);if(!current.rows[0])return reply.code(404).send({code:'COLLECTION_NOT_FOUND',message:'Подборка не найдена'});const c=current.rows[0];await pool.query('UPDATE collections SET title=$1,description=$2,visibility=$3 WHERE id=$4',[input.title??c.title,input.description===undefined?c.description:input.description,input.visibility??c.visibility,id]);const result=await pool.query(`${collectionSelect} WHERE c.id=$1`,[id,request.user.sub]);return serializeCollection(result.rows[0]);});
  app.delete('/collections/:id',{preHandler:requireUser},async(request,reply)=>{const{id}=z.object({id:z.string().uuid()}).parse(request.params);await pool.query('UPDATE collections SET deleted_at=now() WHERE id=$1 AND user_id=$2',[id,request.user.sub]);return reply.code(204).send();});
  app.post('/collections/:id/entries',{preHandler:requireUser},async(request,reply)=>{const{id}=z.object({id:z.string().uuid()}).parse(request.params);const{entryId}=z.object({entryId:z.string().uuid()}).parse(request.body);const result=await pool.query(`INSERT INTO collection_entries(collection_id,map_entry_id,sort_order) SELECT $1,$2,COALESCE((SELECT max(sort_order)+1 FROM collection_entries WHERE collection_id=$1),0) WHERE EXISTS(SELECT 1 FROM collections WHERE id=$1 AND user_id=$3 AND deleted_at IS NULL) AND EXISTS(SELECT 1 FROM map_entries WHERE id=$2 AND user_id=$3 AND deleted_at IS NULL) ON CONFLICT DO NOTHING RETURNING collection_id`,[id,entryId,request.user.sub]);if(!result.rows[0])return reply.code(403).send({code:'ADD_DENIED',message:'Можно добавлять только свои отметки в свои подборки'});await pool.query('UPDATE collections SET places_count=(SELECT count(DISTINCT e.place_id) FROM collection_entries ce JOIN map_entries e ON e.id=ce.map_entry_id WHERE ce.collection_id=$1) WHERE id=$1',[id]);return reply.code(201).send({ok:true});});
  app.delete('/collections/:id/entries/:entryId',{preHandler:requireUser},async(request,reply)=>{const{id,entryId}=z.object({id:z.string().uuid(),entryId:z.string().uuid()}).parse(request.params);await pool.query('DELETE FROM collection_entries WHERE collection_id=$1 AND map_entry_id=$2 AND EXISTS(SELECT 1 FROM collections WHERE id=$1 AND user_id=$3)',[id,entryId,request.user.sub]);await pool.query('UPDATE collections SET places_count=(SELECT count(DISTINCT e.place_id) FROM collection_entries ce JOIN map_entries e ON e.id=ce.map_entry_id WHERE ce.collection_id=$1) WHERE id=$1',[id]);return reply.code(204).send();});
  app.patch('/collections/:id/order',{preHandler:requireUser},async(request)=>{const{id}=z.object({id:z.string().uuid()}).parse(request.params);const{entryIds}=z.object({entryIds:z.array(z.string().uuid()).max(200)}).parse(request.body);await tx(async(client)=>{for(let i=0;i<entryIds.length;i++)await client.query('UPDATE collection_entries SET sort_order=$1 WHERE collection_id=$2 AND map_entry_id=$3 AND EXISTS(SELECT 1 FROM collections WHERE id=$2 AND user_id=$4)',[i,id,entryIds[i],request.user.sub]);});return{ok:true};});
  app.post('/collections/:id/follow',{preHandler:requireUser},async(request,reply)=>{const{id}=z.object({id:z.string().uuid()}).parse(request.params);const result=await pool.query(`INSERT INTO collection_follows(collection_id,user_id) SELECT $1,$2 WHERE EXISTS(SELECT 1 FROM collections c WHERE c.id=$1 AND c.visibility='PUBLIC' AND c.deleted_at IS NULL) ON CONFLICT DO NOTHING RETURNING collection_id`,[id,request.user.sub]);if(result.rows[0])await pool.query('UPDATE collections SET followers_count=followers_count+1 WHERE id=$1',[id]);return reply.code(201).send({following:true});});
  app.delete('/collections/:id/follow',{preHandler:requireUser},async(request,reply)=>{const{id}=z.object({id:z.string().uuid()}).parse(request.params);const result=await pool.query('DELETE FROM collection_follows WHERE collection_id=$1 AND user_id=$2 RETURNING collection_id',[id,request.user.sub]);if(result.rows[0])await pool.query('UPDATE collections SET followers_count=greatest(0,followers_count-1) WHERE id=$1',[id]);return reply.code(204).send();});
  app.post('/collections/:id/add-all-to-wishlist',{preHandler:requireUser},async(request)=>{const{id}=z.object({id:z.string().uuid()}).parse(request.params);const result=await pool.query(`INSERT INTO map_entries(user_id,place_id,entry_type,title,description,visibility,marker_icon_id)
    SELECT $2,e.place_id,'WISHLIST',p.name,'Добавлено из подборки '||c.title,u.default_visibility,e.marker_icon_id FROM collections c JOIN collection_entries ce ON ce.collection_id=c.id JOIN map_entries e ON e.id=ce.map_entry_id JOIN places p ON p.id=e.place_id JOIN users u ON u.id=$2
    WHERE c.id=$1 AND c.deleted_at IS NULL AND pinory_entry_visible(c.user_id,c.visibility,$2) AND NOT EXISTS(SELECT 1 FROM map_entries mine WHERE mine.user_id=$2 AND mine.place_id=e.place_id AND mine.deleted_at IS NULL) RETURNING id`,[id,request.user.sub]);return{created:result.rowCount};});
};
