import type { FastifyPluginAsync } from 'fastify';
import { z } from 'zod';
import { requireUser } from '../auth.js';
import { pool, tx } from '../db.js';
import { notifyUser } from '../services/notifications.js';

const reaction=z.enum(['WANT_HERE','ALSO_VISITED','LIKE']);

export const interactionRoutes:FastifyPluginAsync=async(app)=>{
  app.get('/entries/:id/social',{preHandler:requireUser},async(request,reply)=>{const{id}=z.object({id:z.string().uuid()}).parse(request.params);
    const visible=await pool.query(`SELECT e.user_id FROM map_entries e WHERE e.id=$1 AND e.deleted_at IS NULL AND pinory_entry_visible(e.user_id,e.visibility,$2)`,[id,request.user.sub]);if(!visible.rows[0])return reply.code(404).send({code:'ENTRY_NOT_FOUND',message:'Место недоступно'});
    const counts=await pool.query(`SELECT reaction_type,count(*)::int count FROM entry_reactions WHERE map_entry_id=$1 GROUP BY reaction_type`,[id]);const mine=await pool.query('SELECT reaction_type FROM entry_reactions WHERE map_entry_id=$1 AND user_id=$2',[id,request.user.sub]);
    const companions=await pool.query(`SELECT ec.user_id,ec.status,u.display_name,u.avatar_url FROM entry_companions ec JOIN users u ON u.id=ec.user_id WHERE ec.map_entry_id=$1 ORDER BY ec.created_at`,[id]);
    const source=await pool.query(`SELECT other.id,u.display_name FROM map_entries target JOIN map_entries other ON other.place_id=target.place_id AND other.user_id=$2 AND other.entry_type='VISITED' AND other.deleted_at IS NULL JOIN users u ON u.id=other.user_id WHERE target.id=$1 AND target.user_id<>$2 LIMIT 1`,[id,request.user.sub]);
    return{counts:Object.fromEntries(counts.rows.map(r=>[r.reaction_type,Number(r.count)])),mine:mine.rows.map(r=>r.reaction_type),companions:companions.rows.map(r=>({userId:r.user_id,status:r.status,displayName:r.display_name,avatarUrl:r.avatar_url})),mergeSource:source.rows[0]?{entryId:source.rows[0].id,displayName:source.rows[0].display_name}:null};
  });
  app.post('/entries/:id/reactions/:type',{preHandler:requireUser},async(request,reply)=>{const{id,type}=z.object({id:z.string().uuid(),type:reaction}).parse(request.params);
    const target=await pool.query(`SELECT e.user_id,e.place_id,e.marker_icon_id,p.name FROM map_entries e JOIN places p ON p.id=e.place_id WHERE e.id=$1 AND e.deleted_at IS NULL AND pinory_entry_visible(e.user_id,e.visibility,$2)`,[id,request.user.sub]);if(!target.rows[0])return reply.code(404).send({code:'ENTRY_NOT_FOUND',message:'Место недоступно'});if(target.rows[0].user_id===request.user.sub)return reply.code(400).send({code:'OWN_REACTION',message:'Это ваше место'});
    const inserted=await tx(async client=>{const result=await client.query('INSERT INTO entry_reactions(map_entry_id,user_id,reaction_type) VALUES($1,$2,$3) ON CONFLICT DO NOTHING RETURNING reaction_type',[id,request.user.sub,type]);if(type==='WANT_HERE')await client.query(`INSERT INTO map_entries(user_id,place_id,entry_type,title,visibility,marker_icon_id) SELECT $1,$2,'WISHLIST',$3,u.default_visibility,$4 FROM users u WHERE u.id=$1 AND NOT EXISTS(SELECT 1 FROM map_entries WHERE user_id=$1 AND place_id=$2 AND deleted_at IS NULL)`,[request.user.sub,target.rows[0].place_id,target.rows[0].name,target.rows[0].marker_icon_id]);return Boolean(result.rows[0]);});
    if(inserted)await notifyUser({userId:target.rows[0].user_id,actorUserId:request.user.sub,type:type==='LIKE'?'ENTRY_LIKED':type,entityType:'ENTRY',entityId:id});return reply.code(201).send({active:true});
  });
  app.delete('/entries/:id/reactions/:type',{preHandler:requireUser},async(request,reply)=>{const{id,type}=z.object({id:z.string().uuid(),type:reaction}).parse(request.params);await pool.query('DELETE FROM entry_reactions WHERE map_entry_id=$1 AND user_id=$2 AND reaction_type=$3',[id,request.user.sub,type]);return reply.code(204).send();});

  app.post('/entries/:id/companions',{preHandler:requireUser},async(request,reply)=>{const{id}=z.object({id:z.string().uuid()}).parse(request.params);const{userId}=z.object({userId:z.string().uuid()}).parse(request.body);const owned=await pool.query('SELECT id FROM map_entries WHERE id=$1 AND user_id=$2 AND entry_type=\'VISITED\' AND deleted_at IS NULL',[id,request.user.sub]);if(!owned.rows[0])return reply.code(403).send({code:'OWNER_ONLY',message:'Приглашать может автор воспоминания'});const added=await pool.query(`INSERT INTO entry_companions(map_entry_id,user_id,invited_by_user_id) SELECT $1,$2,$3 WHERE EXISTS(SELECT 1 FROM follows a JOIN follows b ON b.follower_id=a.following_id AND b.following_id=a.follower_id WHERE a.follower_id=$3 AND a.following_id=$2) ON CONFLICT(map_entry_id,user_id) DO UPDATE SET status='PENDING' RETURNING user_id`,[id,userId,request.user.sub]);if(!added.rows[0])return reply.code(403).send({code:'FRIENDS_ONLY',message:'Можно пригласить только взаимного друга'});await notifyUser({userId,actorUserId:request.user.sub,type:'COMPANION_INVITE',entityType:'ENTRY',entityId:id});return reply.code(201).send({status:'PENDING'});});
  app.patch('/entries/:id/companions/me',{preHandler:requireUser},async(request,reply)=>{const{id}=z.object({id:z.string().uuid()}).parse(request.params);const{status}=z.object({status:z.enum(['CONFIRMED','DECLINED'])}).parse(request.body);const result=await pool.query(`UPDATE entry_companions SET status=$1,confirmed_at=CASE WHEN $1='CONFIRMED' THEN now() ELSE NULL END WHERE map_entry_id=$2 AND user_id=$3 RETURNING invited_by_user_id`,[status,id,request.user.sub]);if(!result.rows[0])return reply.code(404).send({code:'INVITE_NOT_FOUND',message:'Приглашение не найдено'});if(status==='CONFIRMED')await notifyUser({userId:result.rows[0].invited_by_user_id,actorUserId:request.user.sub,type:'COMPANION_CONFIRMED',entityType:'ENTRY',entityId:id});return{status};});

  app.post('/entries/:id/merge',{preHandler:requireUser},async(request,reply)=>{const{id}=z.object({id:z.string().uuid()}).parse(request.params);const{sourceEntryId}=z.object({sourceEntryId:z.string().uuid()}).parse(request.body);const source=await pool.query(`SELECT source.user_id FROM map_entries target JOIN map_entries source ON source.id=$2 AND source.place_id=target.place_id AND source.entry_type='VISITED' AND source.deleted_at IS NULL AND pinory_entry_visible(source.user_id,source.visibility,$3) WHERE target.id=$1 AND target.user_id=$3 AND target.entry_type='VISITED' AND target.deleted_at IS NULL`,[id,sourceEntryId,request.user.sub]);if(!source.rows[0])return reply.code(409).send({code:'MERGE_UNAVAILABLE',message:'Воспоминания должны относиться к одному месту'});
    await tx(async client=>{await client.query('INSERT INTO memory_merges(target_entry_id,source_entry_id,requested_by_user_id) VALUES($1,$2,$3) ON CONFLICT DO NOTHING',[id,sourceEntryId,request.user.sub]);await client.query(`INSERT INTO map_entry_media(map_entry_id,media_id,sort_order) SELECT $1,em.media_id,100+em.sort_order FROM map_entry_media em WHERE em.map_entry_id=$2 ON CONFLICT DO NOTHING`,[id,sourceEntryId]);});await notifyUser({userId:source.rows[0].user_id,actorUserId:request.user.sub,type:'MEMORY_MERGED',entityType:'ENTRY',entityId:sourceEntryId,payload:{targetEntryId:id}});return{merged:true};});
};
