import{z}from'zod';
export const entryTypes=['VISITED','WISHLIST','STORY']as const;export const visibilities=['PRIVATE','FOLLOWERS','PUBLIC']as const;export const EntryTypeSchema=z.enum(entryTypes);export const VisibilitySchema=z.enum(visibilities);export type EntryType=z.infer<typeof EntryTypeSchema>;export type Visibility=z.infer<typeof VisibilitySchema>;
export const CoordinatesSchema=z.object({lat:z.number().min(-90).max(90),lng:z.number().min(-180).max(180)});export type Coordinates=z.infer<typeof CoordinatesSchema>;
export const UserSchema=z.object({id:z.string().uuid(),telegramUserId:z.string(),telegramUsername:z.string().nullable(),displayName:z.string(),bio:z.string().nullable(),avatarUrl:z.string().nullable(),homeCity:z.string().nullable(),homeCoordinates:CoordinatesSchema.nullable().optional(),isOnboardingCompleted:z.boolean(),quickStartCompleted:z.boolean().default(false),isFollowing:z.boolean().optional(),isFriend:z.boolean().optional(),stats:z.object({followers:z.number(),following:z.number(),friends:z.number(),visited:z.number(),wishlist:z.number(),collections:z.number()}).optional()});export type User=z.infer<typeof UserSchema>;
export const PlaceSchema=z.object({id:z.string().uuid(),name:z.string(),description:z.string().nullable().optional(),categoryCode:z.string(),categoryName:z.string(),coordinates:CoordinatesSchema,city:z.string().nullable(),region:z.string().nullable(),countryName:z.string().nullable(),countryCode:z.string().nullable(),address:z.string().nullable(),entriesCount:z.number().default(0),visitedCount:z.number().default(0),wishlistCount:z.number().default(0),popularity:z.number().default(0)});export type Place=z.infer<typeof PlaceSchema>;
export const MediaSchema=z.object({id:z.string().uuid(),originalUrl:z.string(),mediumUrl:z.string(),thumbnailUrl:z.string(),width:z.number(),height:z.number()});
export const MapEntrySchema=z.object({id:z.string().uuid(),userId:z.string().uuid(),placeId:z.string().uuid(),entryType:EntryTypeSchema,title:z.string(),description:z.string().nullable(),visitDate:z.string().nullable(),visibility:VisibilitySchema,icon:z.string(),iconColor:z.string(),commentsEnabled:z.boolean(),viewsCount:z.number(),commentsCount:z.number(),createdAt:z.string(),expiresAt:z.string().nullable(),author:UserSchema.pick({id:true,displayName:true,avatarUrl:true,telegramUsername:true}),place:PlaceSchema,media:z.array(MediaSchema).default([])});export type MapEntry=z.infer<typeof MapEntrySchema>;
export const CreatePlaceSchema=z.object({name:z.string().trim().min(2).max(120),categoryCode:z.string().default('other'),coordinates:CoordinatesSchema,city:z.string().trim().max(100).optional(),region:z.string().trim().max(120).optional(),countryName:z.string().trim().max(100).optional(),countryCode:z.string().trim().length(2).transform((value)=>value.toUpperCase()).optional(),address:z.string().trim().max(500).optional()});
const optionalDate=z.preprocess((value)=>value===''||value===null?undefined:value,z.string().date().optional());
const EntryInputObject=z.object({placeId:z.string().uuid().optional(),place:CreatePlaceSchema.optional(),entryType:EntryTypeSchema,title:z.string().trim().min(2).max(120),description:z.string().trim().max(3000).optional(),visitDate:optionalDate,visibility:VisibilitySchema,markerIconCode:z.string().default('pin'),commentsEnabled:z.boolean().default(true),collectionIds:z.array(z.string().uuid()).max(20).default([])});
export const CreateEntrySchema=EntryInputObject.refine((value)=>Boolean(value.placeId||value.place),'Нужно выбрать или создать место');export type CreateEntryInput=z.infer<typeof CreateEntrySchema>;export const UpdateEntrySchema=EntryInputObject.omit({placeId:true,place:true}).partial();
export const CreateCommentSchema=z.object({text:z.string().trim().min(1).max(1000),parentCommentId:z.string().uuid().optional()});export const CreateCollectionSchema=z.object({title:z.string().trim().min(2).max(120),description:z.string().trim().max(2000).optional(),visibility:VisibilitySchema.default('PUBLIC'),entryIds:z.array(z.string().uuid()).max(200).default([])});export const UpdateProfileSchema=z.object({displayName:z.string().trim().min(2).max(80).optional(),bio:z.string().trim().max(300).nullable().optional(),homeCity:z.string().trim().max(100).nullable().optional(),homeCoordinates:CoordinatesSchema.nullable().optional(),isOnboardingCompleted:z.boolean().optional(),quickStartCompleted:z.boolean().optional(),defaultVisibility:VisibilitySchema.optional()});
export const bboxSchema=z.string().transform((value,ctx)=>{const nums=value.split(',').map(Number);if(nums.length!==4||nums.some(Number.isNaN)){ctx.addIssue({code:z.ZodIssueCode.custom,message:'bbox должен быть west,south,east,north'});return z.NEVER;}const[west,south,east,north]=nums as[number,number,number,number];if(west< -180||east>180||south< -90||north>90||west>=east||south>=north){ctx.addIssue({code:z.ZodIssueCode.custom,message:'Некорректные границы bbox'});return z.NEVER;}return{west,south,east,north};});
export interface CursorPage<T>{items:T[];nextCursor:string|null}export interface AuthResponse{accessToken:string;refreshToken:string;user:User}export interface ApiError{code:string;message:string;details?:unknown}
export function canView(visibility:Visibility,isOwner:boolean,isFollower:boolean){return isOwner||visibility==='PUBLIC'||visibility==='FOLLOWERS'&&isFollower}export function popularityScore(input:{uniqueViews:number;opens:number;publicEntries:number;comments:number;wishlists:number;collectionAdds:number;collectionFollows:number;ageHours:number}){const activity=input.uniqueViews*1.2+input.opens*.35+input.publicEntries*3+input.comments*2.2+input.wishlists*2.8+input.collectionAdds*2+input.collectionFollows*2.4;return Math.round(activity/Math.pow(1+Math.max(input.ageHours,0)/72,.65)*100)/100}
